from __future__ import annotations

from typing import Protocol

from personal_os.domain.entities import (
    Approval,
    AuditEvent,
    CommandReceipt,
    Commitment,
    FinancialTransaction,
    Intent,
    Project,
    ScheduleBlock,
    ScheduleProposal,
    TransactionClassification,
    WorldFact,
)


class IntentRepository(Protocol):
    def add(self, entity: Intent) -> None: ...
    def get(self, entity_id: str) -> Intent | None: ...
    def list_for_user(self, user_id: str) -> list[Intent]: ...


class CommitmentRepository(Protocol):
    def add(self, entity: Commitment) -> None: ...
    def get(self, entity_id: str) -> Commitment | None: ...
    def list_for_user(self, user_id: str) -> list[Commitment]: ...


class ProposalRepository(Protocol):
    def add(self, entity: ScheduleProposal) -> None: ...
    def get(self, entity_id: str) -> ScheduleProposal | None: ...
    def list_for_user(self, user_id: str) -> list[ScheduleProposal]: ...


class BlockRepository(Protocol):
    def add(self, entity: ScheduleBlock) -> None: ...
    def list_for_user(self, user_id: str) -> list[ScheduleBlock]: ...


class CommandReceiptRepository(Protocol):
    def add(self, entity: CommandReceipt) -> None: ...
    def get(self, idempotency_key: str) -> CommandReceipt | None: ...


class ApprovalRepository(Protocol):
    def add(self, entity: Approval) -> None: ...
    def find_by_idempotency_key(self, key: str) -> Approval | None: ...
    def list_for_user(self, user_id: str) -> list[Approval]: ...


class WorldFactRepository(Protocol):
    def add(self, entity: WorldFact) -> None: ...
    def find_confirmed_by_label(self, user_id: str, label: str) -> WorldFact | None: ...


class ProjectRepository(Protocol):
    def add(self, entity: Project) -> None: ...
    def primary_for_user(self, user_id: str) -> Project | None: ...
    def list_for_user(self, user_id: str) -> list[Project]: ...


class TransactionRepository(Protocol):
    def add(self, entity: FinancialTransaction) -> None: ...
    def get(self, entity_id: str) -> FinancialTransaction | None: ...
    def list_for_user(self, user_id: str) -> list[FinancialTransaction]: ...


class ClassificationRepository(Protocol):
    def add(self, entity: TransactionClassification) -> None: ...
    def latest_for_transaction(self, transaction_id: str) -> TransactionClassification | None: ...


class AuditRepository(Protocol):
    def append(self, entity: AuditEvent) -> None: ...
    def list_for_user(self, user_id: str, limit: int = 100) -> list[AuditEvent]: ...


class UnitOfWork(Protocol):
    intents: IntentRepository
    commitments: CommitmentRepository
    proposals: ProposalRepository
    blocks: BlockRepository
    approvals: ApprovalRepository
    receipts: CommandReceiptRepository
    world_facts: WorldFactRepository
    projects: ProjectRepository
    transactions: TransactionRepository
    classifications: ClassificationRepository
    audit: AuditRepository

    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, *args: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
